// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI9dJL4f5GHAChcoL9kCky77FgAWg5TNY',
    appId: '1:549178539079:web:7c1eee178d5089c4b3c562',
    messagingSenderId: '549178539079',
    projectId: 'biomarcadores-5182a',
    authDomain: 'biomarcadores-5182a.firebaseapp.com',
    storageBucket: 'biomarcadores-5182a.firebasestorage.app',
    measurementId: 'G-4ZSWLHZ4GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ChVVm9QpCSRSuGcq2hwym433XUVnCS8',
    appId: '1:549178539079:android:6120e7195bcae3abb3c562',
    messagingSenderId: '549178539079',
    projectId: 'biomarcadores-5182a',
    storageBucket: 'biomarcadores-5182a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxFAhEim2HzvGhJdN8QtXNi3h925-9QPA',
    appId: '1:549178539079:ios:caed7dbbb2376d45b3c562',
    messagingSenderId: '549178539079',
    projectId: 'biomarcadores-5182a',
    storageBucket: 'biomarcadores-5182a.firebasestorage.app',
    iosBundleId: 'com.example.biomarcadores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxFAhEim2HzvGhJdN8QtXNi3h925-9QPA',
    appId: '1:549178539079:ios:caed7dbbb2376d45b3c562',
    messagingSenderId: '549178539079',
    projectId: 'biomarcadores-5182a',
    storageBucket: 'biomarcadores-5182a.firebasestorage.app',
    iosBundleId: 'com.example.biomarcadores',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI9dJL4f5GHAChcoL9kCky77FgAWg5TNY',
    appId: '1:549178539079:web:a61fbba6885adec6b3c562',
    messagingSenderId: '549178539079',
    projectId: 'biomarcadores-5182a',
    authDomain: 'biomarcadores-5182a.firebaseapp.com',
    storageBucket: 'biomarcadores-5182a.firebasestorage.app',
    measurementId: 'G-4VZ6WZPXTC',
  );

}